SELECT SUM(CURRENT_GOLD) FROM CUSTOMERLOG WHERE CUSTOMERLOG_DAY = 3 AND CUSTOMER_STATE = 'SERVED';

SELECT SUM(CURRENT_GOLD) FROM CUSTOMERLOG WHERE CUSTOMER_STATE = 'SERVED';

SELECT * FROM gamestate;
UPDATE gamestate SET current_day = 3 WHERE gameState_id = 1;

SELECT CURRENT_GOLD FROM customerlog WHERE customer_state = 'SERVED';

SELECT COUNT(*) TOTAL_CUSTOMER FROM CUSTOMERLOG WHERE CUSTOMERLOG_DAY = 3 AND CUSTOMER_STATE = 'SERVED' OR CUSTOMER_STATE = 'LEFT';

