SELECT SUM(CURRENT_GOLD) FROM CUSTOMERLOG WHERE CUSTOMERLOG_DAY = 3 AND CUSTOMER_STATE = 'SERVED';

SELECT SUM(CURRENT_GOLD) FROM CUSTOMERLOG WHERE CUSTOMER_STATE = 'SERVED';

SELECT * FROM gamestate;
UPDATE gamestate SET current_day = 3 WHERE gameState_id = 1;

SELECT CURRENT_GOLD FROM customerlog WHERE customer_state = 'SERVED';

SELECT COUNT(*) TOTAL_CUSTOMER FROM CUSTOMERLOG WHERE CUSTOMERLOG_DAY = 3 AND CUSTOMER_STATE = 'SERVED' OR CUSTOMER_STATE = 'LEFT';

SELECT MENU_NAME, COUNT(*) 
    FROM CUSTOMERLOG C1 JOIN MENU M1 ON C1.MENU_ID = M1.MENU_ID 
    WHERE C1.CUSTOMERLOG_DAY = 3 AND C1.CUSTOMER_STATE = 'SERVED'
    GROUP BY M1.menu_id;
